apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-sqs-sa
  namespace: inference
  annotations:
    eks.amazonaws.com/role-arn: "${KEDA_ROLE_ARN}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-sa
  namespace: inference
  annotations:
    eks.amazonaws.com/role-arn: "${KEDA_ROLE_ARN}"
