apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opti-inference.fullname" . }}
  labels: {{ include "opti-inference.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "opti-inference.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "opti-inference.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "opti-inference.fullname" . }}-sa
      nodeSelector:
        node-type: gpu
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: inference
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SQS_QUEUE_URL
              value: {{ .Values.keda.sqsQueueUrl | quote }}
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION | quote }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 90
            periodSeconds: 30
