apiVersion: v1
kind: Service
metadata:
  name: {{ include "opti-inference.fullname" . }}
  labels: {{ include "opti-inference.labels" . | nindent 4 }}
spec:
  selector: {{ include "opti-inference.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opti-inference.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opti-inference.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
